/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladorbo.EstudianteBo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelovo.EstudianteVo;

/**
 *
 * @author leale
 */
public class Consultas extends java.awt.Dialog {
    private DefaultTableModel modelo;
    /**
     * Creates new form Consultas
     */
    public Consultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Correo Institucional");
        modelo.addColumn("Correo Personal");
        modelo.addColumn("Celular");
        modelo.addColumn("Fijo");
        modelo.addColumn("Programa");
        TDatos.setModel(modelo);
        List<EstudianteVo> estudiantes = new EstudianteBo().consultarEstudiantes();
        for (EstudianteVo estudiante : estudiantes) {
            String fila[] = {estudiante.getNombres(), estudiante.getApellidos(), estudiante.getNacimiento(), estudiante.getCorreoInst(), estudiante.getCorreoPersonal(), String.valueOf(estudiante.getCelular()), String.valueOf(estudiante.getFijo()), estudiante.getPrograma()};
            modelo.addRow(fila);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        TipoConsulta = new javax.swing.JComboBox<>();
        Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDatos = new javax.swing.JTable();
        Limpiar = new javax.swing.JButton();
        Texto = new java.awt.TextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correo Institucional", "Apellido", "Programa", "Cantidad", "FechaNacimiento", "Celular" }));
        TipoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoConsultaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(TipoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, -1));

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        TDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Nacimiento", "Correo institucional", "Correo personal", "Celular", "Fijo", "Programa"
            }
        ));
        jScrollPane1.setViewportView(TDatos);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 60, 520, 290));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        Texto.setText("");
        Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 190, -1));

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LimpiarActionPerformed
    

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String tipoConsulta = (String) TipoConsulta.getSelectedItem();
        List<EstudianteVo> estudiantes = null;
        if (tipoConsulta.equals("Apellido")) {
            estudiantes = new EstudianteBo().consultarApellido(Texto.getText());
        } else if (tipoConsulta.equals("Programa")) {
           estudiantes = new EstudianteBo().consultarPrograma(Texto.getText());
        } else if (tipoConsulta.equals("FechaNacimiento")) {
            estudiantes = new EstudianteBo().consultarFecha(Texto.getText());
        } else if (tipoConsulta.equals("Celular")) {
            estudiantes = new EstudianteBo().consultarCelular(Long.parseLong(Texto.getText()));
        } else if (tipoConsulta.equals("Correo Institucional")) {
            estudiantes = new ArrayList();
            estudiantes.add(new EstudianteBo().consultarCorreo(Texto.getText()));
        } else if (tipoConsulta.equals("Cantidad")) {
            String mensaje = "La cantidad de estudiantes son: " + new EstudianteBo().cantidadEstudiante(Texto.getText());
            JOptionPane.showMessageDialog(this, mensaje);
        }
        for (EstudianteVo estudiante : estudiantes) {
            String fila[] = {estudiante.getNombres(), estudiante.getApellidos(), estudiante.getNacimiento(), estudiante.getCorreoInst(), estudiante.getCorreoPersonal(), String.valueOf(estudiante.getCelular()), String.valueOf(estudiante.getFijo()), estudiante.getPrograma()};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_ConsultarActionPerformed

    private void TipoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoConsultaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TipoConsultaActionPerformed

    private void TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consultas dialog = new Consultas(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTable TDatos;
    private java.awt.TextField Texto;
    private javax.swing.JComboBox<String> TipoConsulta;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
